sonar.projectKey=HernanLopez5620_FRONTEND_-FINANSYS
sonar.organization=HernanLopez5620
sonar.projectName=FinanSys Frontend
sonar.projectVersion=1.0

sonar.sources=lib
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**

sonar.sourceEncoding=UTF-8

